config/routes.rb
Rails.application.routes.draw do
  
  root :to => "web/welcome#show"

  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
      get 'sign_in', to: 'sessions#new', as: 'sign_in'
      delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

      
    resources :users
      get 'sign_up', to: 'users#new', as: 'sign_up'
      get 'my_profile', to: 'users#show', as: 'my_profile'
      get 'edit_profile', to: 'users#edit', as: 'edit_profile'

    get 'my_groups', to: 'groups#index', as: 'my_groups'  
    resources :groups do
      resource :user_group, only: [:create, :destroy]
        post 'join_group', to: 'user_groups#create', as: 'join_group'
        delete 'leave_group', to: 'user_groups#destroy', as: 'leave_group'
      
        resources :ballots, only: [:new]
        resources :ratings, only: [:new]
        resources :votings, except: [:new] do
          post 'vote', to: 'votings#vote', as: 'vote'
          post 'rate', to: 'votings#rate', as: 'rate'
          get 'display_results', to: 'votings#display_results', as: 'display_results'
          get 'hide_results', to: 'votings#hide_results', as: 'hide_results'
        end  
    end
  end
  
  namespace :admin do
    resources :users
  end
  
end

app/models/voting.rb
class Voting < ApplicationRecord
  validates :title, :question, presence: true
  validates_associated :options

  belongs_to :group, class_name: 'Group'
  belongs_to :author, class_name: 'User'
  has_many :users, through: :group, class_name: 'User'
  has_many :options, class_name: 'Option', dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true, reject_if: :all_blank
  has_many :votes, through: :options, class_name: 'Vote'

  scope :ballots, -> { where(type: 'Ballot') }
  scope :ratings, -> { where(type: 'Rating') }
end

app/controllers/web/votings_controller.rb
class Web::VotingsController < Web::ApplicationController
  before_action :set_voting, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: :update

  def index
    @votings = Voting.all
  end

  def show; end

  def edit; end

  def create
    @group = Group.find(params[:group_id])
    @voting = @group.votings.create(voting_params)

    if @voting.save!
      flash[:notice] = "#{@voting.type} was successfully created."
      redirect_to(group_voting_path(id: @voting.id))
    else
      render(:new)
    end
  end

  def update
    if @voting.update(voting_params)
      flash[:notice] = "#{@voting.type} was successfully updated."
      redirect_to(group_voting_path(@voting))
    else
      render(:edit)
    end
  end

  def destroy
    @voting = Voting.find(params[:id])
    @group = Group.find(@voting.group_id)
    @voting.destroy
    flash[:notice] = "#{@voting.type} was successfully deleted."
    redirect_to(group_path(@group.id))
  end

  def vote
    @voting = Voting.includes(:options).find_by_id(params[:voting_id])
    vote = current_user.votes.create({ option_id: params[:option][:id] })
    if vote.save!
      flash[:notice] = 'Your vote was successfully recorded.'
      redirect_to(group_voting_path(id: @voting.id))
    else
      flash[:error] = 'Something went wrong.'
      render(:show)
    end
  end

  def rate
    @voting = Voting.includes(:options).find_by_id(params[:voting_id])
    params['value'][0].values[0].each do |key, value|
      current_user.votes.create({ option_id: key, score: value })
    end
    flash[:notice] = 'Your rating was successfully recorded.'
    redirect_to(group_voting_path(id: @voting.id))
  end

  def display_results
    @voting = Voting.find_by_id(params[:voting_id])
    if @voting.type == 'Rating'
      @chart_data = {}
      @voting.options.map do |option|
        @chart_data[option.value] = option.average_score
      end
    end
    render(turbo_stream: turbo_stream.replace('display', partial: 'hide', locals: { chart_data: @chart_data }))
  end

  def hide_results
    @voting = Voting.includes(:options).find_by_id(params[:voting_id])
    render(turbo_stream: turbo_stream.replace('hide', partial: 'display'))
  end

  private

  def set_voting
    @voting = Voting.includes(:options).find(params[:id])
  end

  def voting_params
    params.require(:voting).permit(
      :title, :question, :type, :active, :start_date, :stop_date, :author_id,
      options_attributes: [:id, :value, :_destroy]
    )
  end
end

app/views/web/votings/_ballot_vote_form.html.erb
<%= form_tag group_voting_vote_path(voting_id: @voting.id) do %>
  <% @voting.options.each do |option| %>
    <div class="h5 row row-cols-auto">
      <div class="col">
        <li class="mb-2">
          <%= option.value %>
        </li>
      </div>    
      <div class="col float-right"">
        <%= radio_button_tag 'option[id]', option.id %>
      </div>   
    </div>
  <% end %>
  <div class="text-center"><%= submit_tag 'Vote', class: 'btn btn-lg btn-primary' %></div>
<% end %>

app/views/web/votings/_display.html.erb
<turbo-frame id="display">
  <div class="d-flex flex-row-reverse mb-3 text_link">
    <%= link_to "Show results", group_voting_display_results_path(voting_id: @voting.id), class: "toggle_link"  %>
  </div>
</turbo-frame>  

app/views/web/votings/_form_voting.html.erb
<%= simple_form_for @ballot, as: :voting, url: group_votings_path do |f| %>
  <%= f.hidden_field :type, value: "Ballot" %>
  <%= f.hidden_field :active, value: true %>
  <%= f.hidden_field :author_id, value: current_user.id %>
  <div class="mb-3">
    <%= f.input :title %>
  </div> 
  <div class="mb-3">
    <%= f.input :question, as: :text, input_html: { rows: 3 , :style => 'width: 100%'} %>
  </div> 
  <div class="row">
    <div class="mb-3 col">
      <%= f.input :start_date, as: :date, html5: true %>
    </div>
    <div class="mb-3 col">
      <%= f.input :stop_date, as: :date, html5: true %>
    </div>
  </div> 

  <h5 class="card-title text-center mt-2">Response options</h5>
  
    <%= f.simple_fields_for :options do |opt| %>
      <%= render 'option_fields', f: opt %>
    <% end %>

    <div class='links'>
      <%= link_to_add_association f, :options, class: "btn btn-sm btn-info" do %>
        <i class="fas fa-plus"></i>&nbsp;&nbsp;<%= "Add option" %>
      <% end %>
    </div>        
  <div class="mb-2 mt-3 text-center">
    <%= f.button :submit, "Create ballot", class: 'btn btn-lg mb-3 btn-primary btn-floating' %>
  </div> 
<% end %>

app/views/web/votings/_hide.html.erb
<turbo-frame id="hide">
  <div class="d-flex flex-row-reverse mb-3 text_link">
    <%= link_to "Hide results", group_voting_hide_results_path(voting_id: @voting.id), class: "toggle_link" %>
  </div>  
  <%= render 'results' %>
</turbo-frame>

app/views/web/votings/_option_fields.html.erb
<div class="nested-fields row d-flex mb-3">
  <% if @voting.type == "Ballot" %>
    <div class="col-10"> <%= f.input :value, label: "Option" %></div>
    <div class="col-2 align-self-end">
      <% unless f.index == 0 || f.index == 1 %>
        <%= link_to_remove_association "Delete", f, class: "btn btn-sm btn-secondary"%>
      <% end %>
    </div>
  <% else %>
    <div class="col-10"> <%= f.input :value, label: "Object" %></div>
      <div class="col-2 align-self-end">
        <% unless f.index == 0 %>
          <%= link_to_remove_association "Delete", f, class: "btn btn-sm btn-secondary"%>
        <% end %>
      </div>
  <% end %>
</div> 

app/views/web/votings/_rating_vote_form.html.erb
<%= form_tag group_voting_rate_path(voting_id: @voting.id) do |f  | %>
  <% @voting.options.each do |option| %>
    <div class="h5">
      <ul>
        <li class="mb-5">
          <%= option.value %>
          <div class="range">
            <%= range_field "value[][score]", option.id, min: 1, max: 10, step: 1, onchange: "nextElementSibling.value=value", class: "form-range" %>
            <output>5</output>
          </div>
        </li>
      </ul>    
    </div>
  <% end %>
  <div class="text-center"><%= submit_tag 'Rate', class: 'btn btn-lg btn-primary mt-4' %></div>
<% end %>

app/views/web/votings/_results.html.erb
<hr />
<% if @voting.type == "Ballot" %>
  <div class="h5 row justify-content-center">
    <div class="col-auto" style="min-width: 50%">
      <table class="table table-hover"> 
        <tbody>
          <% @voting.options.each do |option| %>
            <tr>
              <td><%= option.value %></td>
              <td class="text-center"><%= option.votes.count %></td>
            </tr>
          <% end %>
            <tr class="table-info">
              <td>Total votes: </td>
              <td class="text-center"><%= @voting.votes.count %></td>
            </tr>
        </tbody> 
      </table>
    </div>
  </div>
<% else %>
  <%= bar_chart @chart_data, 
    max: 10,
    height: "20em",
    width: "auto",
    label: "Average rating",
    colors: ["#0d6efd", "#0dcaf0", "#20c997", "#d63384", "#6f42c1", "#ffc107"],
    loading: "Loading..." %>   
  <div class="h5 text-center mt-3">
    Total rates: <%= @voting.votes.count / @voting.options.count %> 
  </div>
<% end %>  

app/views/web/votings/edit.html.erb
<div class="container-fluid centered bg-img">
  <div class="card shadow-sm p-3 pb-0" style="width: 40rem;">
    <div class="card-body">
      <h5 class="card-title text-center">Edit</h5>
      <%= simple_form_for @voting, as: :voting, url: group_votings_path do |f| %>
        <div class="mb-3">
          <%= f.input :title %>
        </div> 
        <div class="mb-3">
         <%= f.input :question, as: :text, input_html: { rows: 3 , :style => 'width: 100%'} %>
        </div> 

        <div class="row">
          <div class="mb-3 col">
            <%= f.input :start_date, as: :date, html5: true %>
          </div>
          <div class="mb-3 col">
            <%= f.input :stop_date, as: :date, html5: true %>
          </div>
        </div>

        <%= f.simple_fields_for :options do |opt| %>
          <%= render 'option_fields', f: opt %>
        <% end %>

        <div class='links'>
          <%= link_to_add_association f, :options, class: "btn btn-sm btn-info" do %>
            <i class="fas fa-plus"></i>&nbsp;&nbsp;<%= "Add option" %>
          <% end %>
        </div>    
        <div class="mb-3 mt-4 spread">
          <%= f.button :submit, "Confirm", formaction: group_voting_path(@voting.group_id), class: 'btn btn-lg btn-primary btn-floating' %>
          <%= f.button :submit, "< Back", formaction: group_voting_path(@voting.group_id), formmethod: "get",
              class: 'btn btn-sm btn-outline-secondary btn-floating' %>
        </div> 
      <% end %>
    </div>
  </div>
<div>

app/views/web/votings/index.html.erb
<br><br><br><br><br><br><br>adslkdjlaskdjalskdjlaksdjlaskjdlaksdj<br>

<br><br><br><br><br><br><br>adslkdjlaskdjalskdjlaksdjlaskjdlaksdj<br><br><br><br><br><br><br><br>adslkdjlaskdjalskdjlaksdjlaskjdlaksdj<br>

<br><br><br><br><br><br><br>adslkdjlaskdjalskdjlaksdjlaskjdlaksdj<br><br><br><br><br><br><br><br>adslkdjlaskdjalskdjlaksdjlaskjdlaksdj<br>

app/views/web/votings/show.html.erb
<div class="container-fluid centered bg-img"> 
  <div class="card shadow-sm p-3 pb-0 mb-4 mt-4" style="width: 56rem;">
    <div class="card-body">
      <div class="d-flex flex-row-reverse mb-4">
        <% if @voting.author == current_user %> 
          <%= button_to group_voting_path(@voting.group_id), method: "delete", class: 'btn btn-sm btn-danger' do %>
            <i class="fas fa-trash"></i>&nbsp;&nbsp;<%= "Delete" %>
          <% end %>
          <%= button_to edit_group_voting_path(@voting.group_id), method: "get", class: 'btn btn-sm btn-info me-md-2' do %>
            <i class="fas fa-edit"></i>&nbsp;&nbsp;<%= "Edit" %>
          <% end %>
        <% end %>
      </div>
      <p class="mb-3 card-title">
        <%= @voting.title %>
      </p>
      <hr>
      <div class="row mb-2">
        <div class="col">
          <span>Author: <strong><%= @voting.author.first_name %>&nbsp;<%= @voting.author.last_name %></strong></span>
        </div>
        <div class="col">
          <span>Start date: <strong><%= @voting.start_date %></strong></span>
        </div>
        <div class="col">
          <span>End date: <strong><%= @voting.stop_date %></strong></span>
        </div>
      </div>
      <hr>
      <div class="mb-4 mt-4 h5">
        <span>Question:&nbsp;<%= @voting.question %></span>
      </div>
      <% if current_user.already_voted?(@voting) %>
        <% @voting.options.each do |option| %>
          <div class="h5 row">
            <li class="mb-2">
              <%= option.value %>
            </li>
          </div>
        <% end %>
      <div class="mb-4 mt-4 h3 text-center italic text-warning">You have already voted!</div>
      <% else %>
        <% if @voting.type == "Ballot" %>
          <%= render 'ballot_vote_form' %>
        <% else %>
          <%= render 'rating_vote_form' %>
        <% end %>
      <% end %>
      <%= render 'display' %>
      </div>
    </div>
  </div>
</div>