config/routes.rb
Rails.application.routes.draw do
  
  root :to => "web/welcome#show"

  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
      get 'sign_in', to: 'sessions#new', as: 'sign_in'
      delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

      
    resources :users
      get 'sign_up', to: 'users#new', as: 'sign_up'
      get 'my_profile', to: 'users#show', as: 'my_profile'
      get 'edit_profile', to: 'users#edit', as: 'edit_profile'

    get 'my_groups', to: 'groups#index', as: 'my_groups'  
    resources :groups do
      resource :user_group, only: [:create, :destroy]
        post 'join_group', to: 'user_groups#create', as: 'join_group'
        delete 'leave_group', to: 'user_groups#destroy', as: 'leave_group'
      
        resources :ballots, only: [:new]
        resources :ratings, only: [:new]
        resources :votings, except: [:new] do
          post 'vote', to: 'votings#vote', as: 'vote'
          post 'rate', to: 'votings#rate', as: 'rate'
          get 'display_results', to: 'votings#display_results', as: 'display_results'
          get 'hide_results', to: 'votings#hide_results', as: 'hide_results'
        end  
    end
  end
  
  namespace :admin do
    resources :users
  end
  
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :user_groups, class_name: 'UserGroup', dependent: :destroy
  has_many :users, through: :user_groups, class_name: 'User'
  has_many :votings, class_name: 'Voting', dependent: :destroy
  has_many :ballots, class_name: 'Ballot', dependent: :destroy
  has_many :ratings, class_name: 'Rating', dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/controllers/web/groups_controller.rb
class Web::GroupsController < Web::ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:edit, :update, :destroy]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.includes(:votings).find(params[:id])
  end

  def edit; end

  def create
    @group = current_user.owned_groups.build(group_params)
    if @group.save
      @user_group = UserGroup.create(user_id: current_user[:id], group_id: @group[:id], owner: true)
      redirect_to(group_path(@group[:id]))
    else
      render(:new)
    end
  end

  def update
    if @group.update(group_params)
      flash[:notice] = 'Information was successfully updated'
      redirect_to(group_path(@group[:id]))
    else
      render(:edit)
    end
  end

  def destroy
    if @group.owner == current_user
      @group.destroy
      flash[:notice] = "Group #{@group.title} has been deleted"
      redirect_to(root_path)
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/views/web/groups/edit.html.erb
<div class="container-fluid centered bg-img">
  <div class="card shadow-sm p-3 pb-0" style="width: 24rem;">
    <div class="card-body">
      <h5 class="card-title text-center">Edit group information</h5>
        <%= simple_form_for @group do |f| %>
          <div class="mb-3">
            <%= f.input :title %>
          </div> 
          <div class="mb-3">
            <%= f.input :description, as: :text, input_html: { rows: 7 , :style => 'width: 100%'} %>
          </div> 
          <div class="mb-3 spread">
            <%= f.button :submit, "Confirm", class: 'btn btn-primary btn-floating' %>
            <%= f.button :submit, "< Back", formaction: group_path(@group), formmethod: "get",
                class: 'btn btn-sm btn-outline-secondary btn-floating' %>
          </div>
        <% end %>
    </div>
  </div>
<div>

app/views/web/groups/index.html.erb
<div class="container-fluid centered bg-img">
  <div class="card shadow-sm p-3 pb-0" style="width: 24rem;">
    <div class="card-body">
      <h5 class="card-title text-center mb-3">My groups</h5>
        <% @groups.each do |g| %>
          <div class="mb-2 text_link">
            <%= link_to "#{g.title}", group_path(g) %>   
          </div>
        <% end %>
    </div>
  </div>
<div>

app/views/web/groups/new.html.erb
<div class="container-fluid centered bg-img">
  <div class="card shadow-sm p-3 pb-0" style="width: 28rem;">
    <div class="card-body">
      <h5 class="card-title text-center">Create a new group</h5>
        <%= simple_form_for @group do |f| %>
          <div class="mb-3">
            <%= f.input :title %>
          </div> 
          <div class="mb-3">
            <%= f.input :description, as: :text, input_html: { rows: 7 , :style => 'width: 100%'} %>
          </div>
          <div class="mb-3">
            <%= f.button :submit, "Create group", class: 'btn btn-primary btn-floating' %>
          </div> 
        <% end %>
    </div>
  </div>
<div>

app/views/web/groups/show.html.erb
<div class="container-fluid centered bg-img"> 
  <div class="card shadow-sm p-3 pb-0" style="width: 48rem;">
    <div class="card-body">
      <div class="d-flex flex-row-reverse mb-2">
        <% if @group.owner != current_user%> 
          <% if @group.users.exclude?(current_user) %>
            <%= button_to group_join_group_path(@group), method: "create", class: 'btn btn-sm btn-primary' do %>
              <i class="fas fa-square-plus"></i>&nbsp;&nbsp;<%= "Join group" %>
            <% end %>
          <% else %>
            <%= button_to group_leave_group_path(@group), method: "delete", class: 'btn btn-sm btn-warning' do %>
              <i class="fas fa-arrow-right-from-bracket"></i>&nbsp;&nbsp;<%= "Leave group" %>
            <% end %>
          <% end %>
        <% else %>
          <%= button_to group_path(@group), method: "delete", class: 'btn btn-sm btn-danger' do %>
            <i class="fas fa-trash"></i>&nbsp;&nbsp;<%= "Delete group" %>
          <% end %>
          <%= button_to edit_group_path(@group), method: "get", class: 'btn btn-sm btn-info me-md-2' do %>
            <i class="fas fa-edit"></i>&nbsp;&nbsp;<%= "Edit group" %>
          <% end %>          
        <% end %>
      </div>
      <div class="card-title"><%= @group.title %></div>
      <div class="mb-5 mt-2 h5"><%= @group.description %></div>
      <div class="row">
        <% if @group.owner == current_user%>
          <div class="col-4">
            <%= button_to new_group_ballot_path(@group), method: "get", class: 'btn btn-sm btn-warning' do %>
              <i class="fas fa-bullhorn"></i>&nbsp;&nbsp;<%= "Invite people" %>
            <% end %>
          </div>
        <% else %>
          <div class="col-4">
            <span>Group admin: <strong><%= @group.owner.first_name %>&nbsp;<%= @group.owner.last_name %></strong></span>
          </div>    
        <% end %>
        <div class="col-4">
          <%= button_to new_group_ballot_path(@group), method: "get", class: 'btn btn-sm btn-success' do %>
            <i class="fas fa-check-to-slot"></i>&nbsp;&nbsp;<%= "Create new ballot" %>
          <% end %>
        </div>
        <div class="col-4">
          <%= button_to new_group_rating_path(@group), method: "get", class: 'btn btn-sm btn-success' do %>
            <i class="fas fa-star"></i>&nbsp;&nbsp;<%= "Create new rating" %>
          <% end %>
        </div>
      </div>
      <hr>
      <div class="row no_bullets">
        <div class="col-4">
          <div class="italic mx-3">Group members:</div> 
          <ul>
            <% @group.users.each do |user| %>
              <li><%= user.first_name %></li>
            <% end %>
          </ul>
        </div>
        <div class="col-4">
          <div class="italic mx-3" >Active ballots:</div>  
          <ul class="text_link">
            <% @group.ballots.each do |ballot| %>
              <% if ballot.active %>
                <li>
                  <%= link_to group_voting_path(group_id: params[:id], id: ballot.id) do %>
                    <%= ballot.title %>
                  <% end %>
                </li>
              <% end %>  
            <% end %>
          </ul>
        </div>
        <div class="col-4">
          <div class="italic mx-3">Active ratings:</div> 
            <ul class="text_link">
              <% @group.ratings.each do |rating| %>
                <% if rating.active %>
                  <li>
                    <%= link_to group_voting_path(group_id: params[:id], id: rating.id) do %>
                      <%= rating.title %>
                    <% end %>
                  </li>
                <% end %>  
              <% end %>
            </ul>
        </div>
      </div>  
    </div>
  </div>
</div>