config/routes.rb
Rails.application.routes.draw do
  
  root :to => "web/welcome#show"

  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
      get 'sign_in', to: 'sessions#new', as: 'sign_in'
      delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

      
    resources :users
      get 'sign_up', to: 'users#new', as: 'sign_up'
      get 'my_profile', to: 'users#show', as: 'my_profile'
      get 'edit_profile', to: 'users#edit', as: 'edit_profile'

    get 'my_groups', to: 'groups#index', as: 'my_groups'  
    resources :groups do
      resource :user_group, only: [:create, :destroy]
        post 'join_group', to: 'user_groups#create', as: 'join_group'
        delete 'leave_group', to: 'user_groups#destroy', as: 'leave_group'
      
        resources :ballots, only: [:new]
        resources :ratings, only: [:new]
        resources :votings, except: [:new] do
          post 'vote', to: 'votings#vote', as: 'vote'
          post 'rate', to: 'votings#rate', as: 'rate'
          get 'display_results', to: 'votings#display_results', as: 'display_results'
          get 'hide_results', to: 'votings#hide_results', as: 'hide_results'
        end  
    end
  end
  
  namespace :admin do
    resources :users
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :user_groups, class_name: 'UserGroup', dependent: :destroy
  has_many :groups, through: :user_groups, class_name: 'Group'
  has_many :votings, through: :user_groups, class_name: 'Voting'
  has_many :my_votings, foreign_key: :author_id, class_name: 'Voting'
  has_many :votes, class_name: 'Vote'
  has_many :options, through: :votes, class_name: 'Option'
  has_many :owned_groups, foreign_key: 'owner_id', class_name: 'Group'

  validates :first_name, :last_name, :email, presence: true
  validates :first_name, length: { minimum: 2 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },
                    uniqueness: true

  mount_uploader :avatar, AvatarUploader

  def already_voted?(voting)
    options.any? { |o| o.voting == voting }
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(admin_users_url)
    else
      render(:new_admin_user_url)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(admin_users_path)
    else
      render(:edit)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(admin_users_path)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar, :type)
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      flash[:notice] = 'Account was successfully created. Welcome to Agora!'
      redirect_to(:root)
    else
      render(:new)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = 'Your account was successfully updated'
      redirect_to(my_profile_path)
    else
      render(:edit)
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    flash[:notice] = 'Your account was deleted'
    redirect_to(:sign_in)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :avatar,
      :avatar_cache,
      :type,
    )
  end
end

app/views/admin/users/edit.html.erb
<div class="container-fluid centered admin">
  <div class="card shadow-sm p-3 pb-0" style="width: 24rem;">
    <div class="card-body">
      <h5 class="card-title text-center">Edit user</h5>
        <%= simple_form_for @user, as: :user, url: admin_user_path(@user) do |f| %>
          <div class="mb-3">
            <%= f.input :first_name %>
          </div> 
          <div class="mb-3">
            <%= f.input :last_name %>
          </div> 
          <div class="mb-3">
            <%= f.input :email %>
          </div> 
          <div class="mb-3">
            <%= f.input :password %>
          </div>
          <div class="mb-3">
              <%= f.input :type, as: :select, class: 'form-select form-control', selected: 'User', 
                  collection: ['Admin', 'User'] %>            
          </div> 
          <div class="mb-3 spread">
            <%= f.button :submit, "Confirm", class: 'btn btn-primary btn-floating' %>
            <%= f.button :submit, "< Back", formaction: admin_users_url, formmethod: "get",
                class: 'btn btn-sm btn-outline-secondary btn-floating' %>
          </div> 
        <% end %>
    </div>
  </div>
<div>

app/views/admin/users/index.html.erb
<div class="container-fluid centered admin pt-4">
  <div class="card simple mb-4 pb-2" style="width: 64em;">
    <div class="card-body">
        <div class="row spread mb-4";>
          <div class="col-8">
            <%= button_to new_admin_user_path, method: "get", class: 'btn btn-primary' do %>
              <i class="fas fa-add"></i>
              <%= "Add new user" %>
              <% end %>
          </div>
          <div class="input-group col" style="justify-content: end;">
            <%= search_form_for(@q, url:admin_users_url, method: :get) do |f| %>
            <%= f.search_field :first_name_or_last_name_or_email_cont, class: "form-control rounded", 
                placeholder: "Search" %>
            <% end %>
          </div>
        </div>    
        <h5 class="card-title text-center">Users list</h5>
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= sort_link(@q, :id, "#") %></th>
                <th><%= sort_link(@q, :first_name, "First Name") %></th>
                <th><%= sort_link(@q, :last_name, "Last Name") %></th>
                <th><%= sort_link(@q, :email, "E-mail") %></th>
                <th><%= sort_link(@q, :created_at, "Registration date") %></th>
                <th><%= sort_link(@q, :type, "Type") %></th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= user.first_name %></td>
                  <td><%= user.last_name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.created_at.to_date %></td>
                  <td><%= user.type %></td>
                  <td>
                    <%= button_to edit_admin_user_path(user), method: "get", class: 'btn btn-sm btn-info' do %>
                      <i class="fas fa-edit"></i>
                      <%= "Edit" %>
                    <% end %>
                    <% if current_user.id != user.id %> 
                      <%= button_to admin_user_path(user), method: "delete", class: 'btn btn-sm btn-danger' do %>
                        <i class="fas fa-trash"></i>
                        <%= "Delete" %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <div>
          <%= paginate @users, theme: 'bootstrap-5',
          pagination_class: "pagination-sm flex-wrap justify-content-center", nav_class: "inline" %>
          <%= page_entries_info @users  %>
        </div>
    </div> 
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container-fluid centered bg-img admin"> 
  <div class="card shadow-sm p-3 pb-0" style="width: 24rem;">

    <div class="card-body">
      <h5 class="card-title text-center">Add new user</h5>
        <%= simple_form_for @user, as: :user, url: admin_users_path do |f| %>
          <div class="mb-3">
            <%= f.input :first_name %>
          </div> 
          <div class="mb-3">
            <%= f.input :last_name %>
          </div> 
          <div class="mb-3">
            <%= f.input :email %>
          </div> 
          <div class="mb-3">
            <%= f.input :password %>
          </div>
          <div class="mb-3">
            <%= f.input :type, as: :select, class: 'form-select form-control', selected: 'User', 
                collection: ['Admin', 'User'] %>
          </div> 
          <div class="mb-3 spread">
            <%= f.button :submit, "Add User", class: 'btn btn-primary btn-floating' %>
            <%= f.button :submit, "< Back", formaction: admin_users_url, formmethod: "get",
                class: 'btn btn-sm btn-outline-secondary btn-floating' %>
          </div> 
        <% end %>
    </div>
  </div>
<div>

app/views/admin/users/show.html.slim
h1 User profile
p
  span First Name:&nbsp;
  strong= @user.first_name
p
  span Last Name:&nbsp;
  strong= @user.last_name
p
  span E-mail:&nbsp;
  strong= @user.email

= link_to "Back to users list", admin_users_path