config/routes.rb
Rails.application.routes.draw do
  
  root :to => "web/welcome#show"

  scope module: :web do
    resource :session, only: [:new, :create, :destroy]
      get 'sign_in', to: 'sessions#new', as: 'sign_in'
      delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

      
    resources :users
      get 'sign_up', to: 'users#new', as: 'sign_up'
      get 'my_profile', to: 'users#show', as: 'my_profile'
      get 'edit_profile', to: 'users#edit', as: 'edit_profile'

    get 'my_groups', to: 'groups#index', as: 'my_groups'  
    resources :groups do
      resource :user_group, only: [:create, :destroy]
        post 'join_group', to: 'user_groups#create', as: 'join_group'
        delete 'leave_group', to: 'user_groups#destroy', as: 'leave_group'
      
        resources :ballots, only: [:new]
        resources :ratings, only: [:new]
        resources :votings, except: [:new] do
          post 'vote', to: 'votings#vote', as: 'vote'
          post 'rate', to: 'votings#rate', as: 'rate'
          get 'display_results', to: 'votings#display_results', as: 'display_results'
          get 'hide_results', to: 'votings#hide_results', as: 'hide_results'
        end  
    end
  end
  
  namespace :admin do
    resources :users
  end
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-color  py-0 px-0 d-flex">
  <div class="navbar-brand"><%= link_to image_tag("logo.png", alt: "AGORA", id: "logo"), root_path %>&nbsp;
    <span class="h5 logo-link"><%= link_to "AGORA", root_path %></span>
  </div>
  <% if current_user %>
  <span class="v-line"></span>
  <button class="navbar-toggler mx-4" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <div class="navbar-nav me-auto mb-2 mb-lg-0",>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "My groups", my_groups_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create group", new_group_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div class="spread">
      <% if current_user.is_a?(Admin) %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Admin panel", admin_users_path, class: "nav-link" %>
        </li>
      </ul>
      <% end %>
    </div>
    <div class="mx-2">
      <ul class="navbar-nav pt-1">
      <% if current_user.avatar? %>
      <%= link_to my_profile_path, class: "nav-link" do %>
      <li>
        <%= image_tag("#{current_user.avatar}", alt: "avatar") %>
      </li>
      <% end %> 
      <% else %>
      <%= link_to my_profile_path, class: "nav-link" do %>
      <li>
        <%= image_tag("anon.png", alt: "avatar") %>
      </li>
      <% end %>                      
      <% end %>
      <%= link_to my_profile_path, class: "nav-link white", style: "padding-left: 0.3em;" do %>
      <li>
        <%= current_user.first_name %>
      </li>
      <% end %> 
    </div>
    <div class="m-2 mx-3" style="white-space: nowrap;">
      <%= button_to "Sign out", sign_out_path, method: "delete", class: 'btn btn-sm btn-secondary'%>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render partial: "/layouts/navbar" %>
      <% flash.each do |type, msg| %>
        <div class="alert alert-primary alert-dismissible fade show text-center">
          <%= msg %>
        </div>
      <% end %> 
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>